site_name: Programowanie w języku Python - KGiIS AGH

copyright: Copyright 2024 Jakub Staszel

language: pl

theme:
  name: material

nav:
  - Home: index.md
  - Zajęcia 2:
    - Przypisania: zaj2/przypisania.md
    - Pętle: zaj2/petle.md